### PR TITLE
add path support to client connect uri

### LINKED ISSUE #116: Nakama service cannot work behind a reverse proxy
The nakama service cannot run behind a reverse proxy as the client does not accept a path to the connection URI. I dont see why this is not possible from the moment nakama uses websockets and HTTP API calls. The added value of this is also security filtering from broadly available WAFs and other security solutions. This is relevant to https://github.com/heroiclabs/nakama-dotnet/issues/17

### PR DESCRIPTION
**Pull request by h3ph4est7s**
closes #116

### CODE REVIEW

**Review by lugehorsam — APPROVED** [review]

**Review by lugehorsam — CHANGES_REQUESTED** [review]
I am going to document this but there is a bug in the Unity WebGL implementation that prevents calls of more than four parameters to constructors. (Go figure.)

For this reason, could we actually introduce an overload that takes a `Uri, serverKey, adapter, and autoRefreshSession` instead of a separate scheme, host, port? I think this is a bit cleaner anyway.

**Comment by h3ph4est7s** [comment]
Changes added as requested. I wasn't sure if your convension required an instance of Uri or a string so i went with the latter because thats what i noticed is used throughtout the `Client` if you need it as a `Uri` instance i have a changelist ready to be pushed. Closing, thank you very much for the WebGL tip im sure i was going to bump on that at some point!!

**Comment by lugehorsam** [comment]
Ah yeah @h3ph4est7s I meant the `URI` object just so it's explicit.

**Comment by h3ph4est7s** [comment]
Pushed! 😉

**Review by lugehorsam — APPROVED** [review]
Thanks for your contribution 👍

**Pull request merged**
