### PR TITLE
Fix lua error test.

### PR DESCRIPTION
**Pull request by sesposito**
Disable retries for lua error test.
Set delay between matchmaker tickets to better test edge case.

### CODE REVIEW

**Comment by lugehorsam** [comment]
@sesposito is the lua error not serializable to a dictionary? I think our adapter code may rely on that.

**Comment by sesposito** [comment]
It might be serializable to a dictionary, but the JSON that's returned in case of an error at the moment is this: `{"code":13,"error":{},"message":"Some error occured."}`, there's no data field as was previously expected by the test 🤔

**Comment by lugehorsam** [comment]
It's copied by the adapter into the `data` field which is native to all c# exceptions: 

https://github.com/heroiclabs/nakama-dotnet/blob/master/Nakama/HttpRequestAdapter.cs#L108

Basicallk

**Review by lugehorsam — APPROVED** [review]

**Comment by lugehorsam** [comment]
Sorry for holding this up @sesposito , approved and merging.

**Pull request merged**
